# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/110y0vao3YJQA3DddrIinDNtM7md97qFw
"""

import pandas as pd

# Criando uma Series a partir de uma lista
print("Criando uma Series:")
data_series = pd.Series([10, 20, 30, 40, 50])
print(data_series)
print("\n")

# Criando um DataFrame a partir de um dicionário
print("Criando um DataFrame a partir de um dicionário:")
data_dict = {'Nome': ['Alice', 'Bob', 'Charlie', 'David'],
             'Idade': [25, 30, 22, 35],
             'Cidade': ['São Paulo', 'Rio de Janeiro', 'Belo Horizonte', 'Curitiba']}
df_dict = pd.DataFrame(data_dict)
print(df_dict)
print("\n")

# Criando um DataFrame a partir de uma lista de listas
print("Criando um DataFrame a partir de uma lista de listas:")
data_list = [['Ana', 28, 'Salvador'],
             ['Bruno', 32, 'Fortaleza'],
             ['Carla', 26, 'Recife']]
df_list = pd.DataFrame(data_list, columns=['Nome', 'Idade', 'Cidade'])
print(df_list)
print("\n")

# Selecionando uma coluna por rótulo
print("Selecionando a coluna 'Nome':")
nomes = df_dict['Nome']
print(nomes)
print("\n")

# Calculando a média da coluna 'Idade'
print("Calculando a média da coluna 'Idade':")
media_idade = df_dict['Idade'].mean()
print(f"A média das idades é: {media_idade:.2f}")